-- WRITE A QUERY TO CHECK  NAME AND CUSTOMER ID FROM CUSTOMER TABLE 
SELECT Name , Customer_ID
FROM Customer ;

--WRITE A QUERY TO CHECK ALL THE INFORMATION OF EMPLOYEE TABLE
SELECT *
FROM Employee ;

--WRITE A QUERY TO CHECK THE EMPLOYEE DETAILS IN BRANCH PANAGARH , HOWRAH AND KOLKATA 
SELECT *
FROM Employee 
WHERE Branch IN ('Panagarh' , 'Howrah' , 'Kolkata') ;


-- WRITE A QUERY TO CHECK THE EMPLOYEE DETAILS IN BRANCH PANAGARH
SELECT *
FROM Employee 
WHERE Branch = 'Panagarh' ;

--WRITE A QUERY TO CHECK THE EMPLOYEES SALARY > 20000 AND IT SHOULD BE IN ASCENDING ORDER 
SELECT Employee_ID, Name, Branch, Salary
FROM Employee
WHERE Salary >= 20000
ORDER BY Salary ASC;


--WRITE A QUERY TO CHECK THE TOP 5 Employee_ID, Name, Branch , Salary FROM EMPLOYEE TABLE THE SALARY SHOULD BE IN ASCENDING ORDER 
SELECT Employee_ID, Name, Branch , Salary
FROM Employee
ORDER BY Salary ASC
LIMIT 5;


--WRITE A QUERY TO CHECK THE TOP 5 Employee_ID, Name, Branch , Salary FROM EMPLOYEE TABLE 
SELECT Employee_ID, Name, Branch , Salary
FROM Employee
LIMIT 5;
